    name = "RectaRunner"
    version = "1.0.0"
    author = "Turbo"
    description = "RectaRunner!"

[canvas]
width = 256
height = 144

turbo::cfg! {r#"

    [settings]
    resolution = [256, 144]
"#}