[package]
name = "pancake-cat"
version = "1.0.0"
edition = "2021"

[dependencies]
turbo = { version = "3.0.0-alpha.4", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }