name = "Card Search"
    version = "1.0.0"
    author = "Turbo"
    description = "Set Up a Counter in Turbo OS"
    [turbo-os]
    api-url = "https://os.turbo.computer"

[canvas]
width = 132
height = 224
