[package]
name = "pong"
version = "1.0.0"
edition = "2021"

[dependencies]
turbo = { version = ">=2.0.0", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
    